# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=255, unique=True)),
                ('weight', models.IntegerField(default=0)),
                ('choice_int', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255, unique=True)),
                ('answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_view.Answers')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_view.Questions')),
            ],
        ),
    ]
